[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x"]

[phases.install]
cmds = ["npm install -g corepack@0.24.1 && corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd apps/api && pnpm build"]

[start]
cmd = "cd apps/api && pnpm start"

[variables]
PORT = "8080"
NODE_ENV = "production" 