[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && cd apps/api && pnpm build"

[deploy]
startCommand = "cd apps/api && pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PORT = "8080"
NODE_ENV = "production" 